### ISSUE TITLE
Bad argument encoding tuple

### ISSUE THREAD

**Issue by abensoft-williamthome** [zotonic/jsxrecord#5]
I'm facing an issue sending a post request to a Zotonic model.
My post URL is `https://mysite:8443/api/model/mymodel/post/foo` and the body is an empty JSON.
This is the `Resp` value in controller_api:process_done:3, line 173:
```erlang
#{<<"result">> =>
           {#{payload => #{},
              properties =>
                  #{content_type => {<<"application">>,<<"json">>,[]},
                    response_topic =>
                        [<<"reply">>,<<"call-YVLe49c3HZCSSN:fP5wC">>,<<"1">>]},
              qos => 0,retain => false,
              topic =>
                  [<<"model">>,<<"mymodel">>,<<"post">>,<<"foo">>],
              type => publish},
            []},
       <<"status">> => <<"ok">>}
```
If I change all tuples to list the `jsxrecord:encode/1` encodes the value without errors.
To simulate this issue just do this:
```console
jsxrecord:encode({}).
** exception error: bad argument
     in function  jsx_parser:value/4 (/home/williamthome/devel/zotonic/_build/default/lib/jsx/src/jsx_parser.erl, line 163)
```

**UPDATE:**

Note: The request was made via an external API.

**Comment by mworrell** [comment]
~~Did your API `m_get` function return  `{ok, {Result, Rest}}` ?
Or did it return `{Result, Rest}` ?~~

I see that it is a POST.

Maybe you could return something else than a tuple?

There is no JSON ecoding for a tuple (unless it is a known record).
(Unless we come up with some extra encoding/decoding logic for jsxrecord)

**Comment by abensoft-williamthome** [comment]
This is part of my model:
![image](https://user-images.githubusercontent.com/94546997/185615998-f7d2aa61-77e8-46f9-842f-f4e2c8777f1c.png)

If I send https://mysite:8443/api/model/mymodel/get via an external API my model receives it via `m_get/3` and prints the debug, this is the expected behavior, but if I send a request via `post` an error occurs before I can receive it via `m_post/3`. the debug inside the m_post is never fired. In this issue description, the `payload => #{}` is my empty JSON in the POST request, the rest is generated by the Zotonic.

**Comment by abensoft-williamthome** [comment]
Sorry for my mistake.
The expected return for m_post and m_delete is `{ok, Res}`. I don't see anywhere saying this. I was always returning `zotonic_model:return()`.
BTW, now the request returns and the encode error persists. The returned data is:
```erlang
#{<<"result">> =>
    #{payload => #{},
      properties =>
          #{content_type => {<<"application">>,<<"json">>,[]},
            response_topic =>
                [<<"reply">>,<<"call-4CpxxiNXjGVJeiAZp68b">>,<<"1">>]},
      qos => 0,retain => false,
      topic => [<<"model">>,<<"mymodel">>,<<"post">>,<<"foo">>],
      type => publish},
<<"status">> => <<"ok">>}
```
But there is one more mistaked caused by me (or not). The returned data is the Msg from `m_post`:
```erlang
m_post([<<"foo">> | _Rest], Msg, _Context) ->
    {ok, Msg}.
```
The Msg contains the tuple `content_type => {<<"application">>,<<"json">>,[]},` that causes the error.
I think this can be considered a bug. Like the topic, the content_type should be a list of binaries, avoiding the mistake.

Also another point is the payload. It only accepts a JSON body. Sending a text, it returns the error code 415 (Unsupported Media Type). Maybe it can accept other types o data. What I'm trying to do is use the m_post URL as an [endpoint for the SNS from AWS](https://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.prepare.html). I could not create the subscription because the sent data is plain text.

PS: This issue now is more related to Zotonic rather jsxrecord.

**UPDATE**

My workaround for the unsupported media type (cowmachine_decision_core:accept_process_helper/2):
![image](https://user-images.githubusercontent.com/94546997/185942461-3504621e-e23f-48b7-87e8-0df3a5c4620a.png)
By this I can get the subscription URL for the SNS via console.

**UPDATE 2**

The AWS SNS always returns plain text, by this I could not get the payload from the m_post Msg. This limitation is not good for me. Maybe I open a specific issue for this in the Zotonic repository?

**Comment by mworrell** [comment]
@abensoft-williamthome I saw this was still open. Has now been fixed.
